### ISSUE TITLE
Remove players in spectator mode from player tracker

### ISSUE THREAD

**Issue by Zenya4** [cervinakuy/KitPvP#10]
I would like to suggest a config option for the player tracker (compass) to ignore invisible players and players in spectator mode.

It would be really useful for servers with a spectate feature as the spectators can really mess up the compass by causing it to track them instead of other players in the arena.

**Comment by cervinakuy** [comment]
Thanks for the suggestion. I've added a mandatory check which should now ignore players in spectator mode.
