### ISSUE TITLE
Error every hit

### ISSUE THREAD

**Issue by Justsnoopy30** [cervinakuy/KitPvP#114]
**Description of the bug**
An error occurs every hit in kitpvp.
https://paste.gg/p/anonymous/eac81457e4a54da7a75ac73738e9ae39

**Screenshot of /kp debug**
![image](https://user-images.githubusercontent.com/33374736/103446585-dcc12800-4c46-11eb-8211-bbb21c2c3bff.png)

**Comment by cervinakuy** [comment]
Thanks for reporting. This has already been fixed and will be included in the next update.
