### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by ROAD271** [cervinakuy/KitPvP#117]
When a non-op try to join an arena using a sign it shows up in the chat: "[KIT-PVP] You do not have permission.". Which permission should I grant them?
Thank you

**Comment by cervinakuy** [comment]
This is because you have not given the permission for the command which the sign executes (/kp arena <arena name>). Please see the plugin page for the permission name for the arena command.

**Comment by ROAD271** [comment]
Got it.
Thank you so much for your time.
Have a nice day

**Comment by CrazyCharlieBear** [comment]
Where is the permission I cant find it
