### ISSUE TITLE
Having a block as the leave item makes it unusable in whole server

### ISSUE THREAD

**Issue by Pirito10** [cervinakuy/KitPvP#123]
If the material for the leave item is a block, that block can not be used in the whole server, even in non-kitpvp worlds. 
Might be solved checking first if the player is in a kitpvp world, and if it's not, then the BlockPlaceEvent should not be cancelled.

Example config.yml:

```
  Leave:
    Enabled: true
    Name: '&c&lLeave
    Material: BARRIER
    Slot: 8
    BungeeCord:
      Server: Hub
      Enabled: false
    Commands: []
```

In this case, it would be imposible to place a barrier anywhere in the server, or break any block if the item in your hand is a barrier.

**Note:** if the block is in the _left_ hand, it works as it should. This bug just happens for the right hand.

**Comment by cervinakuy** [comment]
Thanks, this has been fixed in [7aae2d6](https://github.com/cervinakuy/KitPvP/commit/7aae2d6bb5640cf7cec1ddbfc90ca3279fdda06f). It will be included in the next update.
