### ISSUE TITLE
Quick Charge becomes Thorns

### ISSUE THREAD

**Issue by abcjoe** [cervinakuy/KitPvP#131]
So i created a Archer kit with a crossbow which has quick charge 3 but when i did /kp kit Archer it gave me a crossbow with thorns 3

![image](https://user-images.githubusercontent.com/79237594/108319536-801ccb00-71fc-11eb-9081-740c68f6c198.png)

![image](https://user-images.githubusercontent.com/79237594/108319210-01279280-71fc-11eb-89d5-e2184303a1a2.png)

Please fix this bug, Thanks :)

**Comment by cervinakuy** [comment]
Thanks, this has been fixed in [93dc6cc](https://github.com/cervinakuy/KitPvP/commit/93dc6cc0f047b351380eb4b8724faf7bbf697949) and will be included in the next update.
