### ISSUE TITLE
Custom health in kit config

### ISSUE THREAD

**Issue by mibibini77** [cervinakuy/KitPvP#133]
**Description of the feature**
a Custom health option for kits
like a certain kit has 30 hp
and maybe a feature that set in ingame a Icon for every Kit for the menu
and maybe a menu that sort the kits in Alphabet

**How the feature is useful**
That means u dont need to give every kit the max health effect and u can make a kit with only 10 hp thats very useful

**Comment by cervinakuy** [comment]
> a Custom health option for kits
like a certain kit has 30 hp

Thanks, this has been added in e6a168c and will be included in the next update.

> and maybe a feature that set in ingame a Icon for every Kit for the menu
and maybe a menu that sort the kits in Alphabet

For a more advanced menu experience, please use an external menu plugin such as AnimatedMenu, ChestCommands, or DeluxeMenus.
