### ISSUE TITLE
Add Support for Speed/Health Attributes in Kits Configs

### ISSUE THREAD

**Issue by Myzumi** [cervinakuy/KitPvP#137]
**Description of the feature**
Add support for each kit config to set specific Health or Speed like 
```
Speed: 2.0
Health: 10 (5 Hearts)
```
**How the feature is useful**
You can create more kits like Ninja having high speed but having less Health, which can be really good to Balance gameplay and Kits

**Comment by cervinakuy** [comment]
> set specific Health
Thanks, this has been added in e6a168c and will be included in the next update.

> set Speed
Potion effects are already automatically detected and saved when using /kp create.
