### ISSUE TITLE
Bug in TrackerListener.java

### ISSUE THREAD

**Issue by Zenya4** [cervinakuy/KitPvP#14]
This is for @cervinakuy ‘s reference. Do remmeber to update the way `nearestplayer` is defined such that the compass does not show that no one is online when the closest player is above the Y-level defined in config.

**Comment by cervinakuy** [comment]
Thanks, this has been fixed in [c4a8ef5](https://github.com/cervinakuy/KitPvP/commit/c4a8ef5edfc041cb2271ba87e08cb25bf4508637).
