### ISSUE TITLE
signs dont work , for defaults and  OP's

### ISSUE THREAD

**Issue by ordillex** [cervinakuy/KitPvP#141]
**Problem** so idk whats happening but i cant use any of the signs like stats and clear after i customized them

**What I have tried** ive tried looking all around the config files to find a error

**Screenshot of /kp debug** https://streamable.com/du42w9 

**Any additional information (copy of config files, screenshots, videos, etc.)**

**Comment by cervinakuy** [comment]
Thanks, I am currently investigating this issue. This has been reported by other users, so it will definitely be fixed in the next update.

**Comment by cervinakuy** [comment]
This has been fixed as of [188642f](https://github.com/cervinakuy/KitPvP/commit/188642f1a1176f97eb3375273d1dc5eb1833b2ec) and will be included in the next update. Thanks.
