### ISSUE TITLE
Coding issue

### ISSUE THREAD

**Issue by Tulipcraft** [cervinakuy/KitPvP#147]
**Problem**
Coding issue

**What I have tried**
rewriting it

**Screenshot of /kp debug**
when i click on the kit nothing happens

**Any additional information (copy of config files, screenshots, videos, etc.)**
Kit:
  Permission: kp.kit.Stormtrooper
  Cooldown: 0
  Level: 0
Inventory:
  Armor:
     Helmet:
      Name: '&f&l Stormtrooper Head'
      Material: PLAYER_HEAD
      Skull: Trooper
    Chestplate:
      Name: '&f&l Stormtrooper Chestplate'
      Material: IRON_CHESTPLATE
    Leggings:
      Name: '&f&l Stormtrooper Leggings'
      Material: IRON_LEGGINGS
    Boots:
      Name: '&f&l Stormtrooper Boots'
      Material: IRON_BOOTS
  Items:
    '0':
      Name: '&f&lBlaster'
      Material: CROSSBOW
      Enchantments:
        UNBREAKING: 10
        POWER: 4
        MULTISHOT: 2
        QUICK_CHARGE: 3
    '1':
      Name: '&f&lThrowable potion of Slowness'
      Material: SPLASH_POTION
      Type: SLOWNESS
      Effects:
        SLOW:
          Upgraded: false
          Extended: false
    '2':
      Name: '&f&lThrowable potion of Slowness'
      Material: SPLASH_POTION
      Type: SLOWNESS
      Effects:
        SLOW:
          Upgraded: false
          Extended: false
    '3':
      Name: '&f&lBullet'
      Material: ARROW
      Amount: 64
    '4':
      Name: '&f&lPower Bullet'
      Material: TIPPED_ARROW
      Amount: 16
      Type: INSTANT_DAMAGE
      Effects:
        HARM:
          Upgraded: false
          Extended: false
    Commands:
    - 'console: This command is run from the console, you can use %player%'
    - 'player: This command is run from the player, you can use %player%'

**Comment by cervinakuy** [comment]
Worked with the individual on this issue.
