### ISSUE TITLE
Coding issue 2

### ISSUE THREAD

**Issue by Tulipcraft** [cervinakuy/KitPvP#148]
**Problem**
Coding issue

**What I have tried**
rewriting everything 

**Screenshot of /kp debug**
none

**Any additional information (copy of config files, screenshots, videos, etc.)**
Kit:
  Permission: kp.kit.phasma
  Cooldown: 0
  Level: 10
Inventory:
  Armor:
    Helmet:
      Name: '&8Captain Phasma'
      Material: PLAYER_HEAD
    Chestplate:
      Name: '&8Phasma''s Chestplate'
      Material: NETHERITE_CHESTPLATE
    Leggings:
      Name: '&8Phasma''s Leggings'
      Material: NETHERITE_LEGGINGS
    Boots:
      Name: '&8Phasma''s Boots'
      Material: NETHERITE_BOOTS
  Items:
    '0':
      Name: '&8Phasma''s Baton'
      Material: STICK
      Enchantments:
        SHARPNESS: 6
    '1':
      Name: '&8Phasma's Blaster Rifle
      Material: CROSSBOW
      Enchantments:
        POWER: 6
        UNBREAKING: 10
        MULTI_SHOT: 3
Effects:
  SLOWNESS:
    Amplifier: 2
    Duration: 100000
    Commands:
    - 'console: This command is run from the console, you can use %player%'
    - 'player: This command is run from the player, you can use %player%'

**Comment by cervinakuy** [comment]
Worked with the individual on this issue.
