### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by popdickle** [cervinakuy/KitPvP#149]
I added a kit sign, but it says "You are not in the arena to perform this action"

I tried adding a arena in config.yml but it didnt work

![2021-05-11_18 11 23](https://user-images.githubusercontent.com/84047827/117891162-0d137580-b27c-11eb-84b4-babaecc645df.png)

also how do i disable some commands of the kit pvp?

**Comment by cervinakuy** [comment]
Run /kp addspawn. That will fix this issue. You cannot select kits (which is what the sign is doing) outside of arena worlds.
