### ISSUE TITLE
Ghost soups

### ISSUE THREAD

**Issue by tommyteschner** [cervinakuy/KitPvP#155]
**Description of the bug**
Sometimes when a player refills soups into their hotbar, the player receives ghost soups. The soups become unusable to heal the player and are just ghost items. Players see the soup in their hotbar and when they hold it, they can see it but other players cannot. It is like they are holding an invisible item that only they can see. This has happened to multiple players across versions. Thanks!

**Screenshot of /kp debug**
https://i.imgur.com/pPNwnLn.png
https://i.imgur.com/d6VpQfM.png

**Additional screenshots or video (if applicable)**
https://medal.tv/clips/54045853/d1337oZ38phd

**Pastebin.com of any relevant .yml files (if applicable)**

**Comment by tommyteschner** [comment]
^ in the top right I have a right CPS counter that shows I am clicking but the soup is not registering (bug happens twice in the video)

**Comment by tommyteschner** [comment]
I saw something about adding an inventory update event once the inventory closes? I'm not sure what that means but will that fix it?

**Comment by cervinakuy** [comment]
Are you still experiencing this problem? If so, can you reach out to me on the support Discord? I'd like to work with you individually. Thanks!

**Comment by cervinakuy** [comment]
Presuming resolved; please re-open if necessary
