### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by RobyWood** [cervinakuy/KitPvP#160]
Scoreboard does not refresh when selecting a kit

![image](https://user-images.githubusercontent.com/87315251/125290725-eb3c7a80-e320-11eb-8ca3-576834d559f0.png)

**Comment by cervinakuy** [comment]
This is not a bug. As specified in the [documentation](https://github.com/cervinakuy/KitPvP/wiki/scoreboard.yml), the scoreboard only refreshes upon kill or death. If you'd like a different behavior, an external scoreboard can be used in place of the built-in one.
