### ISSUE TITLE
Players not with OP are not able to select kits

### ISSUE THREAD

**Issue by ItzArnav** [cervinakuy/KitPvP#161]
Players not with OP are not able to select kits! And also tell how to chage the name from myserver.com to my ip
![image](https://user-images.githubusercontent.com/87792606/126584278-ac365f85-87fd-49b4-9cba-fa636f288ae5.png)

![image](https://user-images.githubusercontent.com/87792606/126584229-61225e0a-123d-4c9e-9dfa-c59e19e932e6.png)

**Comment by LovinLifee** [comment]
This is not an issue with the plugin, but rather it's just misconfigured. You can specify which groups of users have access to the `kp.kit.pvp` permission and then it should work fine.

**Comment by ItzArnav** [comment]
STILL NOT WORKING
![image](https://user-images.githubusercontent.com/87792606/126589671-e69400ad-ece9-41ca-a7bc-421b718949b4.png)

**Comment by DANN160** [comment]
@ItzArnav You can change the scoreboard in the scoreboard.yml file in the plugin config.
Players will not get kits if they have not been given the correct permissions. 
There is load of information on here to help you out

**Comment by ItzArnav** [comment]
**Can you tell the correct Commands**

**Comment by cervinakuy** [comment]
Please read this wiki page, and join the LuckPerms discord for further permissions assistance if necessary.
