### ISSUE TITLE
com.zp4rker.localdb does not properly close Connection objects

### ISSUE THREAD

**Issue by A248** [cervinakuy/KitPvP#166]
**Description of the bug**
`java.sql.Connection` is Auto-Closeable and therefore ought to be closed when used. This isn't purely matter of observation of the specification. SQLite handles native resources which need to be freed when they are no longer in use. By keeping connection objects open, KitPvp will create memory leaks.

Here is one example of a connection which is not closed. com.zp4rker.localdb is filled with such examples:
https://github.com/cervinakuy/KitPvP/blob/ce46ff68b6cafbbb9ee16ad4bb17ea9ffe7d5c8e/src/main/java/com/zp4rker/localdb/Table.java#L130

The recommended way to ensure a connection is closed is to use try-with-resources:
```java
try (Connection connection = sqLite.getSQLConnection()) {
    // Do something with the connection here
}
```
To use multiple closable resources, you declare them separated by semi-colons:
```java
try (Connection connection = sqLite.getSQLConnection(); 
    PreparedStatement statement = connection.prepareStatement("SELECT col1 FROM tabl1 WHERE col2 = ?")) {
    // Do something with the statement here
    // statement.setString(1, "col2Value");
}
```

**Screenshot of /kp debug**
N/a

**Additional screenshots or video (if applicable)**
N/a

**Pastebin.com of any relevant .yml files (if applicable)**
N/a

**Comment by cervinakuy** [comment]
Thanks for your feedback.

However, in that first particular example you mentioned, is the statement not closed a few lines later? https://github.com/cervinakuy/KitPvP/blob/ce46ff68b6cafbbb9ee16ad4bb17ea9ffe7d5c8e/src/main/java/com/zp4rker/localdb/Table.java#L152

**Comment by A248** [comment]
Closing a statement does not close the connection which created it. A connection can have multiple associated statements.

What the current code seems to do is maintain and re-use an open connection which it never closes:
https://github.com/cervinakuy/KitPvP/blob/ce46ff68b6cafbbb9ee16ad4bb17ea9ffe7d5c8e/src/main/java/com/zp4rker/localdb/db/SQLite.java#L19
A connection should not be kept open indeterminably. After a period of time, connection objects may expire and become invalid (Connection#isValid). The exact details of this behavior depends on the JDBC driver implementation. Usually, it's best to rely on libraries which manage the intricacies of connection lifecycles so you don't need to hand-roll a connection pool. The most commonly-deployed such library is HikariCP.

**Comment by cervinakuy** [comment]
@A248 Apologies for taking so long to get back to you on this, university has kept me busy. Thank you again for bringing this to my attention.

I've had numerous users reach out to me about memory leaks for a while now, but I only recently identified its cause to be the poor SQL integration. I've had some freetime, and am working on a SQL recode which include your suggested improvements along with MySQL support.

I'll be making more commits within the next couples days to gradually incorporate it into the codebase to remove zp4rker's implementation, but in the meantime, I'd like your feedback. The changes can be found on the latest commits to [next-update](https://github.com/cervinakuy/KitPvP/tree/next-update).

Thanks.

**Comment by cervinakuy** [comment]
Various commits made in next-update branch to resolve these problems. Please make a separate issue for any suggestions. The main objective of this issue has been resolved.
