### ISSUE TITLE
Splash Instant Health potions don't work in kits

### ISSUE THREAD

**Issue by Dakotaa** [cervinakuy/KitPvP#170]
**Description of the bug**
When creating a kit with splash instant health potions, trying to equip the kit gives an internal error, the specific reason I believe to be "Potion Type is not extendable".

**Screenshot of /kp debug**
https://i.imgur.com/05BgoCL.png

**Additional screenshots or video (if applicable)**
https://pastebin.com/0kFwvgDG

**Comment by cervinakuy** [comment]
Thanks for reporting.

This has been fixed in 27cb909 and will be included in the next update. In the meantime, you can use the beta version available on the #beta channel of the support discord.
