### ISSUE TITLE
Problem pls help

### ISSUE THREAD

**Issue by delta1911** [cervinakuy/KitPvP#171]
**Problem**

**What I have tried**

**Screenshot of /kp debug**

**Any additional information (copy of config files, screenshots, videos, etc.)**

**Comment by delta1911** [comment]
when i try to use ability it shoes pvp is not permitted in this region

**Comment by cervinakuy** [comment]
Solution documented [here](https://github.com/cervinakuy/KitPvP/wiki/Common-Issues). Please read the wiki before asking any additional questions.
