### ISSUE TITLE
Command to select a kit for another player

### ISSUE THREAD

**Issue by powerufljl** [cervinakuy/KitPvP#18]
It would be great if you could give player give functionality for 
example /kp kit archer @p (for player activation) it would work really well with my already existing createyourownmenus plugin

**Comment by cervinakuy** [comment]
Thanks, this feature has been added in [f216765](https://github.com/cervinakuy/KitPvP/commit/f2167653f36ba17c5e971a123af04a622e6b5da1) along with /kp clear [player] functionality.
