### ISSUE TITLE
How to get if player selected this kit or not

### ISSUE THREAD

**Issue by n2g7mutf8** [cervinakuy/KitPvP#185]
Hi, I'm trying to create some special ability for this plugin by using its API.  However, I don't know how to get the name of the kit that the player currently uses. I use ".getName() and .getKitOfPlayer()" but both of them return null when the check event triggered. Does anything wrong with that?

**Comment by cervinakuy** [comment]
Can you include your whole code? Otherwise, something like this should work. Please feel free to re-open if you're still experiencing issues.

```
	@EventHandler
	public void onAbility(PlayerAbilityEvent e) {
		String kitName = Game.getInstance().getArena().getKits().getKitOfPlayer(e.getPlayer().getName()).getName();
		System.out.printf("Ability used! Player used kit: %s\n", kitName);
		if (kitName.equals("Fighter")) {
			// do whatever
		}
	}
```
