### ISSUE TITLE
[SUGGESTION] Player/custom heads as material

### ISSUE THREAD

**Issue by srnyx** [cervinakuy/KitPvP#188]
**Description of the feature**
Allow the use of player heads (username and UUID based) and custom heads (texture-based) as a material throughout the plugin.

**How the feature is useful**
Custom icons for kits and buttons in GUIs.

**Comment by Shivierra** [comment]
It's already possible to do that

**Comment by cervinakuy** [comment]
The built-in menu is intended to be rudimentary. For more advanced menu use-cases, we recommend pairing KitPvP with a dedicated 3rd party menu plugin.
