### ISSUE TITLE
Attempting to add economy in the plugin.

### ISSUE THREAD

**Issue by tubeycat** [cervinakuy/KitPvP#19]
**Problem**
Hi, I was attempting to add the vault plugin into the Kitpvp plugin so I can make the kits cost money, I seem to know what I am doing but I hit a roadblock. In game/Kits java class, I am trying to make it check if the player has enough balance to give them the kit, but I am not too sure how to do that, I attempted to check for the cost in the config and if it is less than the amount the player has in their balance, then I would take away that amount of money leaving the player with the result balance, but the if statement did not seem to like it.
**What I have tried**
I have added 'cost' in the config (for every kit) and that should be all, but I needed to automate it to get it to check the kit cost in the config.

**Any additional information (copy of config files, screenshots, videos, etc.)**
One of the config files (basically applied to all)
Kit:
  Permission: kp.kit.archer
  Cooldown: 0
  Level: 0
  **Cost: 0**

**Comment by cervinakuy** [comment]
Hi there, I can take a look for you.

Although it appears you don't have a public fork of this repository, so you do mind posting the code snippet of the part that isn't working for you?

**Comment by cervinakuy** [comment]
Due to inactivity, I will close this issue.
