### ISSUE TITLE
 My leveling system wont work. 

### ISSUE THREAD

**Issue by ImNotArcher** [cervinakuy/KitPvP#192]
When my friend gets a kill, it says he gets the kill but it doesnt give him any exp.

**Comment by cervinakuy** [comment]
Could you provide a copy of your levels.yml?

**Comment by Arth795-scripts** [comment]
https://yaml.helpch.at/ , make sure everything is indented correctly. u can see the proper stuff by looking at https://github.com/cervinakuy/KitPvP/wiki/levels.yml

**Comment by cervinakuy** [comment]
I believe your links aren't pointing to where they are supposed to. I'd recommend pasting your levels.yml into https://paste.helpch.at. Make sure to press the save button in the top right and send me that link

**Comment by cervinakuy** [comment]
Archiving; feel free to re-open if there are still pending items.
