### ISSUE TITLE
Add customizable anti grinding system

### ISSUE THREAD

**Issue by Redwolf223** [cervinakuy/KitPvP#196]
Anti grinder 
This allows you to stop people from killing the same person over and over to get more points

This examples makes it so that you can only earn points for the first 20 kills on the same person during 3 minutes (180 seconds)

antigrinder-enabled: true
# Interval in seconds 
antigrinder-interval: 180
# Max kill
antigrinder-max: 20

This would be great to add in order to block killstreak / levels farming with a friend.

**Comment by cervinakuy** [comment]
I appreciate the feature request, however, I believe this is just too out of scope for KitPvP at the moment.

Alternatively, you can still use KitPvP alongside a 3rd party antigrinding plugin for the same effect.
