### ISSUE TITLE
No kit without perms

### ISSUE THREAD

**Issue by Ka1serBTW** [cervinakuy/KitPvP#205]
**Description of the bug**
Anyone who is not opped cannot choose kit

**Screenshot of /kp debug**
![image](https://user-images.githubusercontent.com/62085802/171088557-1ea1050d-bb75-4316-88c4-b60dfa2aaff6.png)

**Additional screenshots or video (if applicable)**

**Pastebin.com of any relevant .yml files (if applicable)**
I don't know whats relevant and whats not, this is on Spigot 1.8.8

**Comment by cervinakuy** [comment]
https://github.com/cervinakuy/KitPvP/wiki/Setting-up-a-permissions-plugin
