### ISSUE TITLE
New permission to allow players to bypass level requirement for kits

### ISSUE THREAD

**Issue by tommyteschner** [cervinakuy/KitPvP#21]
**Description of the feature**
If you set a level requirement for a kit you can give players a permission node to bypass that requirement so they can use a for example, LEVEL 75 KIT, when only LEVEL 3.

**How the feature is useful**
This feature would be useful for server owners create a store for players to buy kits with real money to skip the grind to a certain level without violating the eula (every player must be able to obtain the kit without spending real world money).

**Comment by jamerzkim** [comment]
how do u set a level requirement?

**Comment by cervinakuy** [comment]
Thanks, this has been added in [97356dc](https://github.com/cervinakuy/KitPvP/commit/97356dc29c0108175dadbee3a3bcf3364589533d) and will be included in the next update.
