### ISSUE TITLE
MySQL database connection: Access denied

### ISSUE THREAD

**Issue by anonynorbi** [cervinakuy/KitPvP#217]
**Description of the bug**
I wanted to synchronize the kitpvp plugin stats accross mutiple servers via a MySQL database, but I keep getting the errors in my console ( pastebin link below to logs). How can I fix it?

**Screenshot of /kp debug**
![image](https://github.com/cervinakuy/KitPvP/assets/96613061/fc6c6a97-c976-48fe-8edb-2ccf803611fc)

**Additional screenshots or video (if applicable)**
https://paste.helpch.at/bulazufari.md

**Pastebin.com of any relevant .yml files (if applicable)**
Not applicable

**Comment by cervinakuy** [comment]
This is not a KitPvP-specific issue. This is an issue with your MySQL server configuration, or, the MySQL credentials you provided in the config.yml are incorrect. I'd advise you to consult Google, ChatGPT, or the [HelpChat](https://discord.com/invite/helpchat) discord for further assistance on this matter.

**Comment by anonynorbi** [comment]
Made it work!
No special characters and numbers in password did the trick. Less secure but if it works then it works. Anyways thanks for this awesome plugin. Keep up the good work!
