### ISSUE TITLE
Add custom arena join items

### ISSUE THREAD

**Issue by tommyteschner** [cervinakuy/KitPvP#22]
**Description of the feature**
You could add more items when you do /kp spawn and customize the slot within the config

**How the feature is useful**
This feature is useful for players who want to create their own shop or leaderboard gui so they can have more items than just two.

**Comment by cervinakuy** [comment]
Thanks, this has been added in [38b075f](https://github.com/cervinakuy/KitPvP/commit/38b076fd5d8172e2355dff7b5ac3b49d308a6687) and will be included in the next update.
