### ISSUE TITLE
Where are permissions

### ISSUE THREAD

**Issue by CrazyCharlieBear** [cervinakuy/KitPvP#221]
**Problem**
Cant find permission for non op players to do ./kp spawn

**What I have tried**
Looking around and messing around with the code

**Screenshot of /kp debug**

**Any additional information (copy of config files, screenshots, videos, etc.)**

**Comment by iiMilan** [comment]
If players encounter a “You do not have permission message“, please learn more about setting up a permissions plugin: https://bit.ly/kp-permissions-setup-1. Otherwise, view a full list of KitPvP permissions: https://bit.ly/kp-permissions

**Comment by cervinakuy** [comment]
Thanks Milan; closing.
