### ISSUE TITLE
Leaderboard bug

### ISSUE THREAD

**Issue by Francescoohh** [cervinakuy/KitPvP#224]
**Description of the bug**
When i kill or die player appear in the leaderboard multiple times but when i stop and restart the kitpvp server it returns normal (i use bungeecord)

**Screenshot of /kp debug**
[https://ibb.co/cFV0ryZ](url)

**Additional screenshots or video (if applicable)**
[https://ibb.co/xmbr7Yv](url)
[https://ibb.co/Lkf3NgT](url)

**Pastebin.com of any relevant .yml files (if applicable)**

**Comment by cervinakuy** [comment]
Should be fixed in [2e415e5](https://github.com/cervinakuy/KitPvP/commit/2e415e59fe22d8ac216e1b67d6117aa5726ee497) which will be included in the next update.
