### ISSUE TITLE
Can break blocks

### ISSUE THREAD

**Issue by KikyoC** [cervinakuy/KitPvP#226]
Hello,
**Description of the bug**
Can break blocs and prevent block break is enabled

**Screenshot of /kp debug**
![image](https://github.com/cervinakuy/KitPvP/assets/85964347/3bb9408d-faee-4f4d-b0b0-b54f32dad3fa)

**Additional screenshots or video (if applicable)**
![image](https://github.com/cervinakuy/KitPvP/assets/85964347/7137dfe0-a8f1-4c4e-8ee3-6fb17ca26568)

**Pastebin.com of any relevant .yml files (if applicable)**
https://pastebin.com/cfhyW5g5

**Comment by cervinakuy** [comment]
This is because you have OP (which grants all permissions) and have the KitPvP bypass block breaking permission (see permissions in Wiki).

In order to prevent this, install a permissions plugin and negate the permission from your rank or individual user.
