### ISSUE TITLE
Help Unbreakable items

### ISSUE THREAD

**Issue by Kristerium** [cervinakuy/KitPvP#228]
**How to get unbreakable items**

**Unbreakable: True**

**Screenshot of /kp debug**

**Any additional information (copy of config files, screenshots, videos, etc.)**

**Comment by cervinakuy** [comment]
config.ymlgithub.comOn Feb 24, 2024, at 8:56 AM, Kristerium ***@***.***> wrote:﻿
How to get unbreakable items
Unbreakable: True
Screenshot of /kp debug
Any additional information (copy of config files, screenshots, videos, etc.)
