### ISSUE TITLE
Plugin doesn't load/start: java.lang.ClassNotFoundException: org.bukkit.SoundCategory

### ISSUE THREAD

**Issue by Lollo-00** [cervinakuy/KitPvP#229]
**Description of the bug**
At some point the plugin completely stopped working after a restart

**Screenshot of /kp debug**
bug is this https://pastebin.com/5ThHiNRy

**Additional screenshots or video (if applicable)**
//

**Pastebin.com of any relevant .yml files (if applicable)**
//

**Comment by cervinakuy** [comment]
Please include a screenshot of /kp debugOn Feb 24, 2024, at 5:33 PM, Lollo ***@***.***> wrote:﻿
Description of the bug
At some point the plugin completely stopped working after a restart
Screenshot of /kp debug
bug is this https://pastebin.com/5ThHiNRy
Additional screenshots or video (if applicable)
//
Pastebin.com of any relevant .yml files (if applicable)
//

**Comment by Lollo-00** [comment]
> Please include a screenshot of /kp debug

The commands don't work because the plugin doesn't even start.  That's why I gave her the error

**Comment by cervinakuy** [comment]
Turns out this is due to a library we use within the plugin. The developer of said library is [working on a fix](https://github.com/CryptoMorin/XSeries/issues/242). I will release a new version of KitPvP with the fix once is published.

**Comment by Lollo-00** [comment]
> Turns out this is due to a library we use within the plugin. The developer of said library is [working on a fix](https://github.com/CryptoMorin/XSeries/issues/242). I will release a new version of KitPvP with the fix once is published.
> 
> Thanks for reporting.

okay, thanks.

**Comment by cervinakuy** [comment]
Fixed in [31d3506](https://github.com/cervinakuy/KitPvP/commit/31d3506f27139c3c8b3ae3b2c2ea8b6f8d84f241)
