### ISSUE TITLE
Arrows and abilities damages players where it's unexpected

### ISSUE THREAD

**Issue by Stardark99** [cervinakuy/KitPvP#23]
Arrows and abilities damages players in regions with pvp: deny and invincible: true

![image](https://user-images.githubusercontent.com/63285633/78658034-f1e07480-78c9-11ea-854e-c004522d0a2b.png)

**Comment by cervinakuy** [comment]
This issue has been solved as of commit [fe900b2](https://github.com/cervinakuy/KitPvP/commit/fe900b218794ea1648bdcaf9d2de4371c0edf952), and will be included in the next update. Thanks!
