### ISSUE TITLE
I can't use signs under a non-OP account in 1.20.4

### ISSUE THREAD

**Issue by imJack6** [cervinakuy/KitPvP#231]
**Description of the bug**
I'm using this plugin on the server side in 1.20.4 and I'm having trouble trying to add signs. It works fine when adding signs, but when an account other than the OP interacts with the sign it doesn't respond at all, even though I Giving kp all the permissions to the default permission group does not help, but when I use the OP account to interact with it, it can be used normally.

**Screenshot of /kp debug**
![image](https://github.com/cervinakuy/KitPvP/assets/58357771/23cecca2-f984-4287-a032-492df97bf190)

**Comment by cervinakuy** [comment]
This is likely due to the spawn-protection setting in server.properties. Try setting it to 0 and see if that fixes your problem.

**Comment by imJack6** [comment]
> This is likely due to the spawn-protection setting in server.properties. Try setting it to 0 and see if that fixes your problem.

It worked, sorry I forgot to consider the features in the original.
