### ISSUE TITLE
bypasscooldown donc work in 1.20

### ISSUE THREAD

**Issue by softpython2884** [cervinakuy/KitPvP#239]
the bypasscooldown doesn't work I tried more on my server it doesn't work :( here are my plugins:

worldedit-bukkit-7.3.0.jar

multiworld.jar

WorldTP-1.4.3.jar

WorldManager-1.2.1.jar

TAB v4.1.4.jar

Skoice.jar

ProtocolLib.jar

PlaceholderAPI-2.11.5.jar

PhantomWorlds-2.0.9.jar

Multiverse-Core-4.3.1.jar

LuckPerms-Bukkit-5.4.102.jar

LPC.jar

KitPvP.jar

HolographicExtension-1.10.9.jar

HolographicDisplays.jar

EssentialsXSpawn-2.21.0-dev+78-c60ed56.jar

EssentialsXDiscordLink-2.21.0-dev+78-c60ed56.jar

EssentialsXDiscord-2.21.0-dev+78-c60ed56.jar

EssentialsXChat-2.21.0-dev+78-c60ed56.jar

EssentialsX-2.21.0-dev+78-c60ed56.jar

**Comment by cervinakuy** [comment]
Please explain in greater detail how you know the permission does not work, and include a screenshot of /kp debug.

**Comment by cervinakuy** [comment]
Closing; assuming resolved. Re-open with previously requested details if issue is persisting.
