### ISSUE TITLE
Abilities don't work properly

### ISSUE THREAD

**Issue by Stardark99** [cervinakuy/KitPvP#24]
A single click consumes more than one use of abilities. It happens mainly with Thunderbolt, but also the others, more rarely.
I think it would be enough to increase an internal cooldown.

![image](https://user-images.githubusercontent.com/63285633/78658402-6e735300-78ca-11ea-99fc-e253a932eafd.png)

**Comment by cervinakuy** [comment]
Should be solved with the latest commits to next-update, to be included in v2.2.2.
