### ISSUE TITLE
Is it possible to have a way around like this?

### ISSUE THREAD

**Issue by HydraBmw** [cervinakuy/KitPvP#241]
same guy from the rekit after a kill question 

Kill:
  SoupReward:
    NoSpace: '%prefix% &c%amount% soups could not be added to your full inventory.'
    Amount: 1
    Delay: 0
    Enabled: false
  Commands:
  - 'console: kp clear %player%'
  - 'console: kp kit %player% %kitpvp_player_kit%'

is there a way to do it like this?
a work around somehow through commands if possible
can u guide me

**Comment by HydraBmw** [comment]
or is there a way to force give a kit to player 
basically doing the same thing as above

**Comment by cervinakuy** [comment]
> Commands:
> 'console: kp clear %player%'
> 'console: kp kit %player% %kitpvp_player_kit%'

What happens when you try these commands?

**Comment by HydraBmw** [comment]
when i try these commands it just clears the kit
it doesnt give the kit again

**Comment by cervinakuy** [comment]
Ah, understood. Unfortunately there is no built-in way to do this at this time. A potential solution is using a 3rd party kit plugin solely for its kit refill functionality and disable this KitPvP's kits, while using KitPvP's other features if you'd like.
