### ISSUE TITLE
Bug with PlaceHolders

### ISSUE THREAD

**Issue by Marcooooo0ooo** [cervinakuy/KitPvP#244]
**Description of the bug**
When i reload the PlaceholderAPI Plugin the placeholder of KitPvP  are no longer shown, If i do the /papi list before it show KITPVP but when i reload the plugin and i'll do again /papi list the KITPVP it's no longer visible

**Screenshot of /kp debug**
![image](https://github.com/cervinakuy/KitPvP/assets/149093804/42ba244e-a931-41b9-9453-019a815dcbc3)

**Additional screenshots or video (if applicable)**
![Immagine 2024-06-01 144140](https://github.com/cervinakuy/KitPvP/assets/149093804/9109faf6-fb28-4cab-bbaf-d6aab8232e6a)
https://youtu.be/XXLZDuyLpIQ I put it on youtube beacuse the file was too large

**Pastebin.com of any relevant .yml files (if applicable)**

**Comment by cervinakuy** [comment]
This has previously been fixed in #235, and will be included in the next update. In the meantime, here is the jar if you would like it early.
[KitPvP.zip](https://github.com/user-attachments/files/15527241/KitPvP.zip)
