### ISSUE TITLE
Interacting with a KitPVP sign brings up the sign editing menu in 1.20.x

### ISSUE THREAD

**Issue by whizvox** [cervinakuy/KitPvP#245]
**Description of the bug**
In the 1.20 update, signs can now be edited by right-clicking on them. For KitPVP's interactable signs, right-clicking on them will do whatever action you gave it, but it'll also bring up the sign-editing menu. If you have build permissions and exit the menu, the top line's color formatting will be removed, and the sign will lose its functionality. If you don't have build permissions and use something like WorldGuard, exiting the menu will display a "Sorry, but you can't place that block here." message.

I think with the build permissions, Minecraft will remove the original sign and place a new one to achieve the effect of "editing" the sign, hence why the sign seems to lose its functionality.

**Screenshot of /kp debug**
![2024-06-03_10 18 46](https://github.com/cervinakuy/KitPvP/assets/8813286/a09fe133-2e8c-43e9-9407-67c645e7e820)

**Additional screenshots or video (if applicable)**
Right-clicking on an interactable sign:
![2024-06-03_10 20 08](https://github.com/cervinakuy/KitPvP/assets/8813286/47e94de2-4a04-483b-9751-1a1db0927eac)

If you have build permissions:
![2024-06-03_10 20 19](https://github.com/cervinakuy/KitPvP/assets/8813286/152b741b-7489-40bc-9f71-289ec7c8939c)

If you don't have build permissions:
![2024-06-03_10 31 03](https://github.com/cervinakuy/KitPvP/assets/8813286/fab70d1b-6577-4be5-9779-de055ca202fa)

**Pastebin.com of any relevant .yml files (if applicable)**
n/a

**Comment by cervinakuy** [comment]
Thanks for reporting. #248 currently working on a fix. Will follow up as things progress

**Comment by cervinakuy** [comment]
Thanks, fixed in [768a7a9](https://github.com/cervinakuy/KitPvP/commit/768a7a9b0d63d4a5f7780fae930d3dd4961660fa) and will be included in next update, see #266.
