### ISSUE TITLE
probblem with the plugin and luckperms bugee

### ISSUE THREAD

**Issue by filmsite** [cervinakuy/KitPvP#247]
**Problem**
plugin doesnt work with luck perms bungee

**What I have tried**
only using luckperms bukit but i need the bungee version for other server

**Screenshot of /kp debug**

**Any additional information (copy of config files, screenshots, videos, etc.)**

**Comment by bowfun** [comment]
Have you tried installing the LuckPerms plugin on both the BungeeCord and Spigot servers, then connecting them with a database? I use this on my network and it works, as it synchronizes permission and group data between the servers by using the database.

**Comment by cervinakuy** [comment]
KitPvP's permissions are not broken; they have been checked many times. Please contact LuckPerm's support for resolving this issue.
