### ISSUE TITLE
Command when a player take a Kit

### ISSUE THREAD

**Issue by Marcooooo0ooo** [cervinakuy/KitPvP#250]
**Problem**
How can I make some commands from the console ONLY when the player takes the kit (So if he does not have permission to take the kit and clicks it it will not activate the command from the console)

**What I have tried**
I use ItemEdit to change the damage of some swords and other things. To give the modified sword I use a plugin command which if I add to the list of commands to execute when I right click (I modify from the menu.yml file) gives me those items even if I don't have access to the kit

**Screenshot of /kp debug**
![image](https://github.com/cervinakuy/KitPvP/assets/149093804/0f878627-d88b-4b37-a333-22484fa4a974)

**Any additional information (copy of config files, screenshots, videos, etc.)**
![image](https://github.com/cervinakuy/KitPvP/assets/149093804/f8c40334-4592-45b2-a873-512459ea7427)
In this case I put from the menu.yml file that when I click to get the Immortal kit from the console a command starts that gives it 64 sticks 
However, if a person does not have permission, this command is executed anyway and I would like it to be executed only when the person CAN have the kit

If I haven't been very clear in my explanation, don't hesitate to ask me for further information
If I haven't been very clear in my explanation, don't hesitate to ask me for further information

**Comment by cervinakuy** [comment]
This is possible using [kit commands](https://github.com/cervinakuy/KitPvP/blob/6954f42c2146122c50fa16707bb8b3a3a198a0a2/src/main/resources/kits/Example.yml#L90-L92) rather than menu commands.
