### ISSUE TITLE
Kit permissions not working properly.

### ISSUE THREAD

**Issue by p3w-YT** [cervinakuy/KitPvP#251]
**Problem**
The permissions for the kits that I have created are not working properly, and people that do not have operator cannot claim/use any kits. (Yes, I have the permission set properly using Luckperms.)

**What I have tried**
I've tried looking up the answer, everywhere and nothing could help. I've even resorted to asking ChatGPT and it also could not help me with my problems.

**Screenshot of /kp debug**
![2024-06-12_20 31 11](https://github.com/cervinakuy/KitPvP/assets/172215956/440afc78-3d75-4d3a-b8af-751a0fff5938)

**Any additional information (copy of config files, screenshots, videos, etc.)**
Copy of all config files:
https://pastebin.com/NRUSD8D3

**Comment by p3w-YT** [comment]
Sorry that this is an hour later but, I can also show my permissions in Luckperms, and everything is properly set, but still the Kits dont work for people that dont that operator. Every command, not just claiming kits using the chest or /kp kit, Even smaller commands like /spawn AKA /kp spawn doesnt work for people that dont have operator. There is a screenshot attached below with the luckperms permissions.
![Screenshot 2024-06-12 215027](https://github.com/cervinakuy/KitPvP/assets/172215956/59424e8d-cfa2-4604-9bb9-80b9f0919d0e)

**Comment by cervinakuy** [comment]
Are you still experiencing this issue? This is frequently due to incorrect LuckPerms configuration.

**Comment by p3w-YT** [comment]
yeah, its still happening. i tried doing everything like looking it up, and even resorting to ask ChatGPT 4o, and nothing worked.

**Comment by cervinakuy** [comment]
I am unable to replicate this bug - likely misconfigured permissions on your end. Please re-open if still experiencing this issue.
