### ISSUE TITLE
Items visual glitch, gets damaged and disappears from inventory until clicked on.

### ISSUE THREAD

**Issue by YaseenAkoub** [cervinakuy/KitPvP#26]
**What is Happening?**
So swords get damaged and break (its a visual glitch) but it actually breaks until I press "E" and click on the slot the sword was on. If the sword died then it brings it back and if it got damaged it sets it to full dura.

Server Version >> Spigot 1.8.8 [KitPvP Version: 2.1.0 (Latest)]

My /KP Debug >> https://prnt.sc/rxg2bd

YouTube Video >> https://youtu.be/MaFk0zncX48

**Comment by cervinakuy** [comment]
Thanks, this has been fixed as of [81a4ef6](https://github.com/cervinakuy/KitPvP/commit/81a4ef643babe1043d6e13069a58794fc84290d6), and will be included in the next update.
