### ISSUE TITLE
Respawn point.

### ISSUE THREAD

**Issue by Cqban** [cervinakuy/KitPvP#260]
Hello, i would like to know if it is possible to put a respawn point, which would not be in the arena where pvp is enabled, and then when you select a kit, it teleports you randomly on one of the arena spawns.

Thank you

**Comment by cervinakuy** [comment]
If I'm understanding your desired setup correctly, yes.

Random spawn/respawn point: Use /kp addspawn to add multiple spawn/respawn points. When executing /kp spawn or respawning, the player will be randomly teleported to one of the multiple set spawn points.

Random arena teleportation upon selecting kit: There isn't an exact feature for this built-in with KitPvP; however, other server owners in the past have either 1) use kit commands ([documentation](https://github.com/cervinakuy/KitPvP/wiki/Creating-a-kit#kit-commands)) to explicitly teleport players to specific coordinates, or 2) use kit commands to run an external randomized spawn teleportation plugin

If you have further questions on this topic please feel free to re-open this issue.
