### ISSUE TITLE
Placeholders not working

### ISSUE THREAD

**Issue by Cqban** [cervinakuy/KitPvP#261]
**Description of the bug**
The placeholders of the plugin aren't working

**Screenshot of /kp debug**
![image](https://github.com/user-attachments/assets/bb84127a-eb5a-4962-b305-17970330bdfc)

**Additional screenshots or video (if applicable)**
![image](https://github.com/user-attachments/assets/df8335d3-3f0d-4f99-87f0-63fe4fa56cbf)
![image](https://github.com/user-attachments/assets/ae22866e-ded9-4b57-92aa-079a1f5991f2)

**Pastebin.com of any relevant .yml files (if applicable)**

**Comment by cervinakuy** [comment]
There is a typo, the placeholder is %kitpvp_stats_**kd**%, not kdr. See https://github.com/cervinakuy/KitPvP/wiki/PlaceholderAPI-placeholders
