### ISSUE TITLE
Sign Problem

### ISSUE THREAD

**Issue by Jehico** [cervinakuy/KitPvP#262]
Hello, I am having problems with the signs, when I click on them I get that error in both minecraft and the console. I have tried adding permissions, but it does not work at all, pls help.

![image](https://github.com/user-attachments/assets/89635be9-1d4d-45c5-8495-4097accadf81)

![image](https://github.com/user-attachments/assets/82ba75c9-5b25-4754-8eaa-26674564c615)

**Comment by cervinakuy** [comment]
Thanks, fixed in [768a7a9](https://github.com/cervinakuy/KitPvP/commit/768a7a9b0d63d4a5f7780fae930d3dd4961660fa) and will be included in next update, see #266.
