### ISSUE TITLE
Items from 1.21 not working despite working in other 1.20 plugins

### ISSUE THREAD

**Issue by Sparkwave2** [cervinakuy/KitPvP#263]
**Problem**
The plugin does not work with 1.21 items even though they exist in the server. They work fine with other 1.20 plugins which dynamically get available items. This plugin seems to have hardcoded item IDs, so to resolve my problem it'd probably either have to not do that or update to 1.21.

**What I have tried**
Putting in the exact item ID

**Screenshot of /kp debug**
![image](https://github.com/user-attachments/assets/30c36c59-9cea-4b25-a497-40ae5a5b6219)

**Any additional information (copy of config files, screenshots, videos, etc.)**

**Comment by cervinakuy** [comment]
Can you explain your issue in more detail or provide kit files that don't work in 1.21? I'm able to both create kits with 1.21 items, and also equip said kits on v2.2.3 on a 1.21 server. No errors or unexpected behavior on my end.

**Comment by cervinakuy** [comment]
Added 1.21 item support and forward compatibility to avoid this happening in the future, see #266. Will be included in next update.
