### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by artit18829** [cervinakuy/KitPvP#265]
**Problem**

**What I have tried**

**Screenshot of /kp debug**

**Any additional information (copy of config files, screenshots, videos, etc.)**

**Comment by artit18829** [comment]
hi

**Comment by artit18829** [comment]
![Screenshot 2024-08-26 231514](https://github.com/user-attachments/assets/e76cef37-7113-45df-bb38-a4e5c9a8ef6e) how fixe

**Comment by cervinakuy** [comment]
https://github.com/cervinakuy/KitPvP/wiki/Common-Issues#pvp-is-not-permitted-in-this-region-message
