### ISSUE TITLE
No coins showing, what to do?

### ISSUE THREAD

**Issue by tochado** [cervinakuy/KitPvP#268]
The coins doesnt count when i kill or die and cant buy anything

Checked the mysql think

![image](https://github.com/user-attachments/assets/3910f2ed-d8f3-4258-9c01-15a5dd420f0b)

Dont have

**Comment by cervinakuy** [comment]
KitPvP does not have a coin system. You may be confusing this repository for another KitPvP plugin GitHub repository.
