### ISSUE TITLE
Custom Player Heads

### ISSUE THREAD

**Issue by DevPraver** [cervinakuy/KitPvP#271]
**Problem**
can you tell how to add custom player heads in menu and in custom join items?

**What I have tried**
i have tried out a few things but they dont work, like in dhub you get to use "base64"
or commandpanels "cps=" so can you tell it?

**Comment by cervinakuy** [comment]
Unfortunately, this is not possible within the menu and custom arena items. For the menu, you can disable KitPvP's menu and use a separate more advanced menu plugin instead.

**Comment by DevPraver** [comment]
> Unfortunately, this is not possible within the menu and custom arena items. For the menu, you can disable KitPvP's menu and use a separate more advanced menu plugin instead.

yes thanks bro, it worked
