### ISSUE TITLE
Give Exp With commands

### ISSUE THREAD

**Issue by ThePsyguy021** [cervinakuy/KitPvP#28]
Ability to give experience and Levels through commands.

This would be useful for shops in giving experience through the purchase of ranks.
For Example if someone purchased an Overlord rank they would be given 100 exp.

**Comment by tommyteschner** [comment]
I agree this definitely needs to be a feature!

**Comment by cervinakuy** [comment]
Thanks, this has been added in 16bf42d and will be included in the next update.
