### ISSUE TITLE
Just a simple question, please help!

### ISSUE THREAD

**Issue by RokioZaki** [cervinakuy/KitPvP#282]
**Problem**
Actually i dont want to use anything other than the kits in this plugin and the abilities.. i dont want this plugin to affect other plugins any tips?

**What I have tried**
disabling the stuff, but i have no idea what im doing

**Screenshot of /kp debug**

**Any additional information (copy of config files, screenshots, videos, etc.)**

**Comment by cervinakuy** [comment]
Please read the wiki for this.
