### ISSUE TITLE
Team Deathmatch and or other gamemodes

### ISSUE THREAD

**Issue by tommyteschner** [cervinakuy/KitPvP#29]
**Description of the feature**
Add team deathmatch so players are sorted into teams that fight one another and whichever team gets the most kills win! Other games would also be amazing! (king of the hill, and so on)

**How the feature is useful**
Adds an extra gamemode for players to have fun with!

**Comment by cervinakuy** [comment]
Thanks but this would be very much into the future and not something I would be pursuing at the moment. I will keep this in mind though!
