### ISSUE TITLE
Use Maven for Dependency Management

### ISSUE THREAD

**Issue by A248** [cervinakuy/KitPvP#3]
Hey cervinakuy,

I'm delighted you chose to open-source KitPvP! I was just wondering if you had considered maven for dependency management. Maven makes it much easier for other developers to hook into your plugin. You should look into it!

A248

**Comment by cervinakuy** [comment]
Thanks for making an issue regarding this.

I've been working on transitioning from Eclipse to IntelliJ, and the hope would be to use IntelliJ's Maven manager which is a bit nicer. I would expect to see this change implemented over the next few days or weeks.

I completely understand that contributing is a bit of a hassle without it, and I appreciate your concern.
