### ISSUE TITLE
help :)

### ISSUE THREAD

**Issue by doragoma** [cervinakuy/KitPvP#30]
**Description of the bug**
i use 1.8spigot (waterfall)

**Screenshot of /kp debug**

**Additional screenshots or video (if applicable)**

**Pastebin.com of any relevant .yml files (if applicable)**
https://cdn.discordapp.com/attachments/524487963804041217/701332866902130708/message.txt
↑plz Download

**Comment by cervinakuy** [comment]
Can you please include the screenshot of your /kp debug? Also, the first error appears to not even be related to my plugin, it says it was caused by SuperLobby.

And if you could include the entire stacktraces/errors so I can track down the cause in my code that would be appreciated.

**Comment by cervinakuy** [comment]
Due to inactivity and the recent bug fixes, this issue has been closed. Please contact me if you are still experiencing this problem.
