### ISSUE TITLE
Sound mapping errors on 1.9

### ISSUE THREAD

**Issue by CRAZYLOL4** [cervinakuy/KitPvP#31]
**Description of the bug**
There is a glitch with sounds how i am missing a sound apparently and when i do /kp addspawn it says it didnt do it but it did. And how sounds are missing when i die and it spams respawning and glitches out.

**Screenshot of /kp debug**

![Screenshot (1705)]
https://user-images.githubusercontent.com/64122907/79944718-d87d2200-849e-11ea-8879-4dc011a4c1fb.png

**Additional screenshots or video (if applicable)**
![Screenshot (1706)]
https://user-images.githubusercontent.com/64122907/79944761-f34f9680-849e-11ea-9d8b-e7e5fb280a9e.png

**Pastebin.com of any relevant .yml files (if applicable)**

**Comment by cervinakuy** [comment]
Thanks, but this has to do with using an [outdated version of your server](https://hub.spigotmc.org/jira/browse/BUILDTOOLS-199). Rather than using regular 1.9, make sure to use the latest, which in this case would be 1.9.4.
