### ISSUE TITLE
Snowball Damage in Arena World

### ISSUE THREAD

**Issue by Hundiii** [cervinakuy/KitPvP#32]
Snowballs deal 2 hearts damage (Default Damage on Blazes). But it should only make Knockback.

1.8.8

**Comment by cervinakuy** [comment]
Thanks, this has been fixed in [b21390c](https://github.com/cervinakuy/KitPvP/commit/b21390c78de6a3fb9978ac12f071bdb99eee162a) and will be included in the next update.
