### ISSUE TITLE
Players lose Killstreak on leave

### ISSUE THREAD

**Issue by tommyteschner** [cervinakuy/KitPvP#34]
**Description of the bug**
When a player has a killstreak and they leave the game it resets to 0

**Screenshot of /kp debug**
https://i.imgur.com/LW6ZTYY.png

**Additional screenshots or video (if applicable)**

**Pastebin.com of any relevant .yml files (if applicable)**

**Comment by cervinakuy** [comment]
Thanks, but this has been fixed in [8a10575](https://github.com/cervinakuy/KitPvP/commit/8a10575eb3147faf49ee05fbe14c7b9ed36511d9), and will be included in the next update.
