### ISSUE TITLE
Please make spawn-on-join turnable.

### ISSUE THREAD

**Issue by SaltyPotata** [cervinakuy/KitPvP#35]
**Description of the feature**
spawn-on-join

**How the feature is useful**
Please make spawn-on-join turnable. It would be a really cool feature and everyone would like it. Because if you like in a combat and you run for your life you can simply quit and automatically get teleported to spawn which I don't want to.

**Comment by cervinakuy** [comment]
Thanks, this has been added and will be included in the next update.
