### ISSUE TITLE
KitPvP Problem

### ISSUE THREAD

**Issue by jamerzkim** [cervinakuy/KitPvP#38]
**Problem**
The KitPvP isn't working for others in my server. When someone joined; they said they needed opp so I am wondering how this can be fixed.

**What I have tried**
Nothing

**Screenshot of /kp debug**
None

**Any additional information (copy of config files, screenshots, videos, etc.)**
None

**Comment by LifelessNerd** [comment]
They probably need certain permissions to use the plugin

**Comment by cervinakuy** [comment]
Yep, as @LifelessNerd said, you probably just need to configure a permissions plugin on your server. I recommend [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/), and here's a [YouTube tutorial](https://www.youtube.com/watch?v=oS6tl5SME_I) on setting that up if you need it.

Please let me know if you have any additional questions, but this issue will be closed.
