### ISSUE TITLE
Potions are not colored

### ISSUE THREAD

**Issue by tommyteschner** [cervinakuy/KitPvP#39]
**Description of the bug**
Regular potions and splash potions are not colored but are all the exact same color of a dark blue even if they are different potions.

**Screenshot of /kp debug**
https://i.imgur.com/Ri8fJLu.png

**Additional screenshots or video (if applicable)**

**Pastebin.com of any relevant .yml files (if applicable)**

**Comment by xpple** [comment]
This is very likely your texture pack...

**Comment by tommyteschner** [comment]
Using default ;-;

**Comment by cervinakuy** [comment]
This has been fixed as of [62071ba](https://github.com/cervinakuy/KitPvP/commit/62071bae04a21164f8ab843d4baa92ebc710686f) and will be included in the next update. Thanks.
