### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by Anton-Sandin** [cervinakuy/KitPvP#4]
Prefixes from GroupManager wont show with the chat enabled from the KitPVP plugin, how do i enable the prefixes? 

I tried: 
      Format: '[{GROUP}] {level} &e{player} &f{message}'
And
      Format: '{prefix} {level} &e{player} &f{message}'

But didnt work.

**Comment by cervinakuy** [comment]
There isn't direct support for rank prefixes in the level chat format.

To use rank prefixes, you have to download [PlaceholderAPI ](https://www.spigotmc.org/resources/placeholderapi.6245/)and [Vault](https://dev.bukkit.org/projects/vault) (+ the Vault extension using /papi ecloud download Vault). Then in your levels.yml, you can add {rank_prefix} which will display the prefix.

**Comment by cervinakuy** [comment]
Assuming the above solution worked for you, I will close this issue. Thanks.
