### ISSUE TITLE
Thunderbolt kit says right click on a player even though I am right clicking on a player

### ISSUE THREAD

**Issue by tommyteschner** [cervinakuy/KitPvP#42]
**Description of the bug**
When you right click someone using the lightning sticks from Thunderbolt it says Right click on a player but I am right clicking on a player.

**Screenshot of /kp debug**
https://i.imgur.com/7C3MsRF.png
https://i.imgur.com/sMzHocA.png
**Additional screenshots or video (if applicable)**

**Pastebin.com of any relevant .yml files (if applicable)**

**Comment by cervinakuy** [comment]
Thanks, this has been fixed in 2.1.2 and is now available on Spigot.
