### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by jamerzkim** [cervinakuy/KitPvP#44]
**Problem**
People in my server that are de-opped cannot get the kits.
It says: You don't have permission. Idk what to do; do I give them op?
**What I have tried**
I looked at your wiki and saw that the page for permissions was taken down.
**Screenshot of /kp debug**

**Any additional information (copy of config files, screenshots, videos, etc.)**

**Comment by cervinakuy** [comment]
This is because you do not have a permissions plugin. I would recommend a plugin such as [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/). [Here](https://www.youtube.com/watch?v=oS6tl5SME_I) is a YouTube tutorial if you need it.
