### ISSUE TITLE
Command signs doesn't work

### ISSUE THREAD

**Issue by Vimppura69** [cervinakuy/KitPvP#47]
After updating the 2.1.1 version the command signs stopped working. Command signs are those signs where you write [kitpvp] and menu/clear/etc and it uses the command for you when you click the sign. In previous version they worked just fine. After updating the plugin I also updated the signs.yml to make sure there weren't any changes. When I click the sign, it doesn't say anything or do anything.

![kuva](https://user-images.githubusercontent.com/64931511/81233399-4b3ddf80-8fff-11ea-859e-7e2f2a1c3331.png)

![kuva](https://user-images.githubusercontent.com/64931511/81233534-804a3200-8fff-11ea-8daa-c273307d1964.png)

**Comment by cervinakuy** [comment]
Thanks, this has been fixed in [d422f90](https://github.com/cervinakuy/KitPvP/commit/d422f90e552dae3223d3ae9fc326f13917e4b825) and is available in 2.1.2 now available on Spigot.
