### ISSUE TITLE
Console access for commands

### ISSUE THREAD

**Issue by Vimppura69** [cervinakuy/KitPvP#48]
In 2.1.1 you made possible to run commands on behalf of another player by using ex. /kp clear <playername>. It would be amazing if they could also be runned via console.

This would be very useful when servers want to run commands like /kp clear or kit automatically without giving permissions to players. This would also make possible to example give players some fun easter egg kits which they couldn't otherwise get etc.

**Comment by cervinakuy** [comment]
Thanks, this has been added in [4cb8368](https://github.com/cervinakuy/KitPvP/commit/4cb83680e2850fe8149cbd028f617780d79010d1). It will be included in the next update.
