### ISSUE TITLE
Item drop and chest opening config broken

### ISSUE THREAD

**Issue by Vimppura69** [cervinakuy/KitPvP#50]
**Description of the bug**
Any items can be dropped and chests opened even tho it's disabled in config. Issue appears with every player, even tho they are not vanilla op. This problem appeared after we updated the plugin to 2.1.1 version. Item drop issue is present with every item, kit or no kit.

**Screenshot of /kp debug**
![kuva](https://user-images.githubusercontent.com/64931511/81236776-a2937e00-9006-11ea-9098-c87438d9ba6d.png)

**Additional screenshot**
![kuva](https://user-images.githubusercontent.com/64931511/81236933-fdc57080-9006-11ea-90c8-03dca53135b1.png)

**Pastebin.com of any relevant .yml files**
https://pastebin.com/9A8wTCxu

**Comment by cervinakuy** [comment]
Joined your server and determined these issues were caused by an external plugin, not KitPvP.
