### ISSUE TITLE
Thunderbolt and Vampire abilities do not work

### ISSUE THREAD

**Issue by tommyteschner** [cervinakuy/KitPvP#52]
**Description of the bug**
Thunderbolt and Vampire abilities do not work

**Screenshot of /kp debug**
https://i.imgur.com/DJQZAfH.png
https://i.imgur.com/d52Fnf1.png

**Comment by cervinakuy** [comment]
Worked with the OP, the issue turned out to be that the kit item name and the item name in the abilities.yml did not match, resulting in the abilities not working.
