### ISSUE TITLE
someone is abusing my archer kit

### ISSUE THREAD

**Issue by noobberry** [cervinakuy/KitPvP#54]
i found out that someone was abusing my archer kit by killing himself with the bow, when he kill himself it counts a kill for him. so he got like 30 kills and reached number 1 on the leaderboard, what is the solution please?

**Comment by cervinakuy** [comment]
Thanks, this has been fixed in [0a2d369](https://github.com/cervinakuy/KitPvP/commit/0a2d3699a47f1960625a8980e6d1efd5c8c4eaa0) and will be included in the next update.
