### ISSUE TITLE
a weird problem

### ISSUE THREAD

**Issue by noobberry** [cervinakuy/KitPvP#55]
when i fall off in the void, i die normally and i get teleported to the spawn point  i made with kitpvp, but when someone who don't have OP this happens: https://youtu.be/BpPFte2FBU0

**Comment by noobberry** [comment]
![2020-05-18_22 08 07](https://user-images.githubusercontent.com/65505454/82261659-bf617700-995f-11ea-9b0b-3975ad58844b.png)

**Comment by cervinakuy** [comment]
I worked with you personally on this, and we concluded the issue with some sort of conflict with WorldGuard.
