### ISSUE TITLE
Error spam when arrow shot

### ISSUE THREAD

**Issue by Ninjablader101** [cervinakuy/KitPvP#58]
**Description of the bug**
Shotting a bow gets a huge error

**Screenshot of /kp debug**
![image](https://user-images.githubusercontent.com/52899751/82702942-f6c27300-9c40-11ea-937c-a32bcc426d92.png)

**Additional screenshots or video (if applicable)**

**Pastebin.com of any relevant .yml files (if applicable)**
https://paste.helpch.at/gadaciweve.pl that is the error

**Comment by cervinakuy** [comment]
Thanks, this has already been fixed in [c69b7a7](https://github.com/cervinakuy/KitPvP/commit/c69b7a7ef08018f5a73f75f0109cabfecb1ad337), and will be included in the next update. I will close this issue once the new version is released.
