### ISSUE TITLE
issue with disabling kit selector and return to hub items

### ISSUE THREAD

**Issue by SnakeAmazing** [cervinakuy/KitPvP#59]
I have disabled the option, but they still appear when I join the server.
https://pastebin.com/gpjECUVX

**Comment by cervinakuy** [comment]
I just tested this on the latest version (2.1.2) and disabled the items. They did not appear. I believe you may have either forgotten to do /kp reload to update the configurations or you're used an outdated version.

Also in the future, please try to use the [issue templates](https://github.com/cervinakuy/KitPvP/issues/new/choose) with the necessary information that way I can be of more assistance.
