### ISSUE TITLE
Kit Dropping 

### ISSUE THREAD

**Issue by itsWarHammer** [cervinakuy/KitPvP#60]
**Description of the feature**
Players Should be able to drop everything in their inventory except the items that come with the kits they are given

**How the feature is useful**
Stops Players with a Strong kit from dropping their kit and giving it to other players

**Comment by cervinakuy** [comment]
I appreciate you making a feature request for this, but this would be detrimental to server performance if the plugin has to iterate over a kit's items constantly to ensure that an item dropped is _only_ of their kit.

**Comment by itsWarHammer** [comment]
maybe have a curse of binding that is invisible ?

**Comment by itsWarHammer** [comment]
AllowKitDropping: false = curse of binding and vanishing on all kit items making them undroppable and also not having them drop on death {binding}
