### ISSUE TITLE
Enderpearl Cooldown

### ISSUE THREAD

**Issue by amrealpatrick** [cervinakuy/KitPvP#63]
**Problem**
When pvping with a kit that has an ender pearl it has a 4-5 cooldown

**What I have tried**
tried looking in the source and config.yml

**Screenshot of /kp debug**

**Any additional information (copy of config files, screenshots, videos, etc.)**
https://streamable.com/irr5ht

**Comment by cervinakuy** [comment]
This is an issue with Essentials, since my plugin does not do any special handling of pvp after using an ender pearl or teleporting in general. Use the solutions discussed in this thread and you should be well on your way.
