### ISSUE TITLE
Certain kit level bypasses

### ISSUE THREAD

**Issue by tommyteschner** [cervinakuy/KitPvP#64]
**Description of the feature**
kp.level.bypass.15 only bypasses the level requirement up to level 15 so that players cannot get kits above the level 15 with the level bypass

**How the feature is useful**
makes the permission better by adding more uses to it

**Comment by cervinakuy** [comment]
Thanks, this has been added in [3cc71bb](https://github.com/cervinakuy/KitPvP/commit/3cc71bba98a3a35af36673fad4f8d6bba9011760) and will be included in the next update. Please note that kp.levelbypass no longer exists.
