### ISSUE TITLE
Save inventory on arena/world leave --> then restoring it on arena join

### ISSUE THREAD

**Issue by tommyteschner** [cervinakuy/KitPvP#65]
**Description of the feature**
Saves the players inventory on arena/world leave and then restores it when they rejoin the arena

**How the feature is useful**
This would help players who have multi world servers instead of bungeecord.

**Comment by cervinakuy** [comment]
Unfortunately adding this feature is outside of the scope of the intention of KitPvP. Players can use PerWorldInventory, Multiverse-Inventories or a variant to manage their inventories across worlds. KitPvP is not meant to do that for you.
