### ISSUE TITLE
Players take damage from abilities in servers below 1.13.2

### ISSUE THREAD

**Issue by YaseenAkoub** [cervinakuy/KitPvP#68]
**Description of the bug**
On 1.13.2 & below servers, players take damage from kit abilities, this is because the latest WorldGuard and WorldEdit only works on 1.13.2-1.15.2 Most the people who use the KitPvP plugin probably use 1.8 (as it's a PVP version) 
_By the way, guns don't do damage even with nokitprotection off!_

**Screenshot of /kp debug**
Lightshot Screenshot: [Click Here!](https://prnt.sc/stmxau)

**Additional screenshots or video (if applicable)**
YouTube Video: [Click Here!](https://www.youtube.com/watch?v=d6tIKeyhKtw)

**Quick feature suggestion...**
Probably make it so we can choose if we want abilities even enabled in certain regions. And also the Bomber kit (it doesn't do damage). Make it so it is also disabled in "pvp: false, invincible: true" regions because It gets super messy especially for new players who join.

**_---------------------------------------------------_**
_I am terrible at explaining sorry..._
**_---------------------------------------------------_**

**Comment by iiMilan** [comment]
Maybe you can make it so people will TP to the arena when they select a kit! @YaseenAkoub 
Hope to help you with this info

- iiMilan

**Comment by YaseenAkoub** [comment]
@iiMilan I've actually thought of doing this a long time ago, but yet again, people cant just right-click a kit and be sent to the arena straight.

Or I can make a quick thing where it warns them for 5 seconds
They're gonna get teleported

Or I can just have PerRegionPerms and add abilities in the PvP region.

**Comment by cervinakuy** [comment]
Fixed in various commits ([1](https://github.com/cervinakuy/KitPvP/commit/140e2d6a84d102695a04d6b864b4003b1a47a898)) ([2](https://github.com/cervinakuy/KitPvP/commit/30cf636be65fad531125016bdd6ed59796954e30)) ([3](https://github.com/cervinakuy/KitPvP/commit/c99548b5b2d5dc961859c52640dfb57705c5cbea)). This will be included in the next update.
