### ISSUE TITLE
Players take damage from damage abilities (vampire, etc.) while being in godmode.

### ISSUE THREAD

**Issue by tommyteschner** [cervinakuy/KitPvP#69]
**Description of the bug**
Players take damage from damage abilities (vampire, thunderbolt) while being in godmode.

**Screenshot of /kp debug**
https://i.imgur.com/Bd4MWV2.png
https://i.imgur.com/CfbGvcD.png

**Comment by cervinakuy** [comment]
Thanks, although godmode does not pertain to my plugin. You would have to reach out to what I assume are the Essentials developers and let them know that their god mode does not work properly.
