### ISSUE TITLE
request :) i really want placeholder support, like hook into papi and create its own placeholders.

### ISSUE THREAD

**Issue by muffinized** [cervinakuy/KitPvP#72]
**Description of the feature**
i really want placeholder support, like hook into papi and create its own placeholders. because i use deluxehub's scoreboard, I cant really display the kills, death etc. i could use the essentials papi ecloud, but i also need the level and XP. my server name is Muffinized, 10 letters, 16 is max. my thing is called KitPVP > Muffinized so its way more. i cant do that as title of scoreboard with kit-pvp's in built scoreboard, but I CAN with deluxehub

**How the feature is useful**
it can make the variety more, because i can make it so it can be animated, extended, with more possibilities of the design of the scoreboard.

**Comment by tommyteschner** [comment]
There is already placeholder support, you can find this on the spigot page

**Comment by cervinakuy** [comment]
As @tommyteschner said, there are already KitPvP PlaceholderAPI placeholders you can use. Take a look at the Overview page and you can find some there.
