### ISSUE TITLE
Minigame Events

### ISSUE THREAD

**Issue by tommyteschner** [cervinakuy/KitPvP#73]
**Description of the feature**
You can type /events and then there would be a GUI that has a list full of events a player can host like sumo, spleef, team deathmatch, lms, brackets, and more. Once players lose the event they would get teleported to a spectator arena. Each event has a different permission to activate it.

**Sumo:** Just like brackets where 2 players are randomly picked to knock each other off on a platform.
**Spleef:** Players spawn with a shovel and break the snow to spleef each other.
**Team Deathmatch:** Players get divided onto 2 teams and then they have to reach 50 kills before the other team does.
**LMS:** Last man standing which means a free for all with no respawns. Whoever is the last wins!
**Brackets:** Players 1v1 each other in a tournament. (It would be cool if you could automatically unlock all kits and be able to use any one in the 1v1)

**How the feature is useful**
This feature would be very very nice because there aren't ANY good event plugins on any plugin site (paid or free) and it would add an extra perk for players to give to donators. It would improve the overall player experience because you could interact with your community by creating events! I would be very grateful if this feature is added and I'm sure others would too!

**Comment by cervinakuy** [comment]
Thanks, but this seems very similar to #29 and I will close this for the same reason I closed the other one.

**Comment by tommyteschner** [comment]
Ah sorry I thought I deleted the other one
