### ISSUE TITLE
Not allow re-entry to spawn

### ISSUE THREAD

**Issue by i-am-soy** [cervinakuy/KitPvP#74]
**Problem**
is there a way to make it so that once you select a kit and leave a worldguard region, you can't re-enter it?

**What I have tried**
i havent tried anything because idk what to do

**Screenshot of /kp debug**
![image](https://user-images.githubusercontent.com/31712285/84926468-705f4c80-b099-11ea-8c07-de8147d6789e.png)

**Any additional information (copy of config files, screenshots, videos, etc.)**
i dont believe anything is necessary because im asking if something exists

**Comment by i-am-soy** [comment]
what im specifically asking for is if there is a way to make it so you cant re-enter a spawn zone once you have a kit selected

**Comment by i-am-soy** [comment]
also is there a way to make it so you cant leave sapawn until you selected a kit

**Comment by iiMilan** [comment]
You could make it so you have a sperate section of the spawn and make it so people will TP to the arena. @i-am-soy

**Comment by TURTL3D** [comment]
I think worldguard has flags that allow / deny entry or exit for a region. I'm not sure though, if you can tie that in with the KitPvP plugin.
