### ISSUE TITLE
Crops get destroyed even when PreventBlockPlacing is set to false

### ISSUE THREAD

**Issue by xpple** [cervinakuy/KitPvP#75]
**Description of the bug**
When a player jumps on a crop the crop gets destroyed and the farmland is reverted back to dirt.

**Pastebin.com of any relevant .yml files (if applicable)**
PreventBlockPlacing: false

**Comment by cervinakuy** [comment]
I believe I recall fixing this around the time this issue was originally created. If this isn't the case, feel free to let me know and I can follow-up.
