### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by Hippir** [cervinakuy/KitPvP#78]
**Description of the feature**
Gives us a command to display the leaderboard (in chat)
or placeholders to display top kills, deaths, kdr, level, etc.
on holographic displays.

**How the feature is useful**
It would allow us to have rewards for top
users without having to check through
the data file to check who has the most.

**Comment by muffinized** [comment]
i agree

**Comment by cervinakuy** [comment]
Thanks, this has been added in 16af5e2 and will be included in the next update.
