### ISSUE TITLE
Ability Recharge & Holding Limit

### ISSUE THREAD

**Issue by TURTL3D** [cervinakuy/KitPvP#82]
**Description of the feature**
Basically, allow an ability to recharge after use. Instead of having a set amount of "ability use", allow player to have an infinite amount, but have a cool-down after a use. Can also have a maximum number of ability before recharging again.

[EXAMPLE 1]: Player has a speed boost ability, but can only use it once every 17 seconds. They can have a maximum of 3 speed boosts ready before recharge starts again. If only used 1 speed boost, only 1 will recharge while the other 2 are ready to use. (Goes on for an infinite amount). Using the ability again won't interrupt the recharge (or you can add this option too [set to true / false]).

**How the feature is useful**
Prevents ability spam, and allows for extended / more frequent PvP engagements.

**Comment by cervinakuy** [comment]
Thanks, ability recharges have been added as of 2.1.6.
