### ISSUE TITLE
Overriding essentials chat

### ISSUE THREAD

**Issue by MeowedAt** [cervinakuy/KitPvP#83]
**Problem**

Overriding essentials chat

**What I have tried**

Changing config in essentials and kp

**Screenshot of /kp debug**

![image](https://user-images.githubusercontent.com/58730469/88475356-e2dc0b80-cf26-11ea-8d70-81f342803e02.png)

**Any additional information (copy of config files, screenshots, videos, etc.)**

We had luckperms prefixes

**Comment by cervinakuy** [comment]
What exactly is the problem you're experiencing?

**Comment by cervinakuy** [comment]
Due to inactivity and a lack of response, I will close this issue.

Please feel free to re-open this if you are still experiencing problems.
