### ISSUE TITLE
Potions given as Mundane Potions despite configuring names

### ISSUE THREAD

**Issue by Firestar772** [cervinakuy/KitPvP#87]
**Description of the bug**
Potions added to kits via /kp create are given as Mundane potions, and are not affected by the "name" config option. 

**Screenshot of /kp debug**
![image](https://user-images.githubusercontent.com/44457766/89451827-06b70280-d71a-11ea-9c97-128d9a7d1113.png)

**Additional screenshots or video (if applicable)**
![image](https://user-images.githubusercontent.com/44457766/89451857-10d90100-d71a-11ea-886e-2859599a100c.png)

![image](https://user-images.githubusercontent.com/44457766/89451872-18000f00-d71a-11ea-8dcc-61ff2dd3c910.png)

**Pastebin.com of any relevant .yml files (if applicable)**

**Comment by Firestar772** [comment]
Some updates after more testing. Server is Spigot 1.8.8. Splash Potions added from client version 1.15.2 become mundane potions, and ignore the name tag as well as the effect time can vary for potions of the same type, as shown above.
Splash Potions added from 1.8.8 are given with the correct name and effect, but the item is wrong, always being given with the texture of a splash potion of slowness. 
![image](https://user-images.githubusercontent.com/44457766/89609904-67d3f880-d836-11ea-99a8-587d523aed37.png)

**Comment by Firestar772** [comment]
Quick additional thing, the color problem appears to only be happening in 1.8.8/9. In 1.15.2 all of the potion colors show correctly, however their names are all still mundane potion.
![image](https://user-images.githubusercontent.com/44457766/89975551-46eb1900-dc23-11ea-8beb-9954bc0a25c3.png)

**Comment by Firestar772** [comment]
Tested the bug on Gregpeg528's Spigot 1.8.8 server and got the same results. At this point it's a plugin bug likely with 1.8.8 Spigot instances and how potions are given rather than a conflict with another plugin, as the only plugins we share are Worldguard and Luckperms.

**Comment by cervinakuy** [comment]
Looking into this, it appears potions are no longer being given as Mundane on newer versions of the plugin, however, they are still missing names that may be specified in the kit file.

I will be working to fix this issue, thanks for reporting

**Comment by cervinakuy** [comment]
Closing, as this was previously fixed (not sure which commit(s), but I just tested it, and names are functional with potions).
