### ISSUE TITLE
How do we change the kits permission?

### ISSUE THREAD

**Issue by BlueOctoling** [cervinakuy/KitPvP#88]
**Problem**
I'm trying to figure out how to change the permissions of kits , butit is said no-where how to do so , on the main page it's only written the permissions list , but not how to change it.
**What I have tried**
I tried going through the files of the plugins , but I saw no-where where to change it.
I'm also checking the Wiki right now , so if I see where we change it.

**Screenshot of /kp debug**
![2020-08-23_14 59 00](https://user-images.githubusercontent.com/70098892/90978877-49b60a00-e551-11ea-9a02-76e502b4275e.png)

**Comment by MioGuldbrand** [comment]
If you go into the plugins folder -> KitPvP -> Kits -> *Kit you want to change permission on* -> Open File -> At the top, it should say "permission: kp.kit.Starter (if it is Starter)", change from what it says to the permission you want to have.
