### ISSUE TITLE
Code is very broken

### ISSUE THREAD

**Issue by LimaBean2091** [cervinakuy/KitPvP#89]
I imported the code into my IDE (eclipse) as a maven project, dependencies loaded fine and all, but the first thing I noticed was that two files had an error, (Resource.java line 23 [Returns type Path, but the variable is defined as String]) so I solved that one by adding .toString(), and another error in some other file that I just added a throws declaration to. Anyways, after the ERRORS were fixed, I didn't modify anything else and I compiled it, and then moved resources to the main jar. Once I loaded the plugin, I got a null pointer in the file: Config.java, it appears that whatever Game.getInstance() returns has not been initialized. So I hardcoded a return value for that just to see if I could fix it. After that ordeal, it seemed to run fine, but when I tried to select a kit /kp kit [kit] it threw a null pointer exception. It appears that in Kits.java (getKitByName), CacheManager is ALSO not initialized. So if you could do something about all of these bugs in the code, it would be greatly helpful, and PLEASE, when you push to GitHub, can you at least make sure that your code works? Thanks.

**Comment by cervinakuy** [comment]
Hi there, thanks for creating this issue. I apologize for pushing unstable code, I realize I should have done this in a separate branch. I will do this in the future. In the mean time, you can checkout the 2nd most recent commit before the recode and it should work fine. Please let me know if you have any additional questions. Thanks!

**Comment by LimaBean2091** [comment]
Thank you for the very quick reply, and thanks for being one of the good developers on github!
