### ISSUE TITLE
TNT block damage is prevented

### ISSUE THREAD

**Issue by switchbranch** [cervinakuy/KitPvP#9]
TNT block damage is prevented even when PreventBlockBreaking is set to FALSE.  Could a toggle be added to config.yml to allow it?

Also, is there a way to make regular TNT blocks place-able as opposed to forcing them to be thrown?  It seems to happen even without any item meta on them, even if given by the /give command via console in any world that has a kit-pvp spawn set.

**Comment by cervinakuy** [comment]
Fixed in the latest two commits [209c70f](https://github.com/cervinakuy/KitPvP/commit/209c70f81ff2845fc3c4d3b96036acc45f129c30) and [711c108](https://github.com/cervinakuy/KitPvP/commit/711c1088dd7111425b3ac5ff5df45bb04015d8a0).

This will be included in the next update. Thank you for reporting!
