### ISSUE TITLE
How to delete permission requirement for kits 

### ISSUE THREAD

**Issue by stalsalwin** [cervinakuy/KitPvP#91]
**Problem**
I want to delete permission requirements for kit but i can't find any whay to do it.

**What I have tried**
i tried deleting (in fighter kit) permission: kp.kit.fighter but that didn't worked. then i installed luckperms plugin and added to default group kp.kit.fighter permission but i still didn't have permission without op.

**Screenshot of /kp debug**/kp

**Any additional information (copy of config files, screenshots, videos, etc.)**

**Comment by cervinakuy** [comment]
There isn't a way to delete a permission requirement for a kit.

It appears that your problem is that you forgot to give your players kp.command.kit. I will close this issue but please re-open it if you are still experiencing problems.
