### ISSUE TITLE
the kp.kit.<custom kit> does not work

### ISSUE THREAD

**Issue by muffinized** [cervinakuy/KitPvP#92]
**Description of the bug**
the kp.kit.<custom kit> does not work

**Screenshot of /kp debug**
![image](https://user-images.githubusercontent.com/66737626/91654577-98791c00-eadc-11ea-84e7-58926197fdd4.png)

**Additional screenshots or video (if applicable)**
permissions:
![image](https://user-images.githubusercontent.com/66737626/91654696-9cf20480-eadd-11ea-9a5d-09f6d403f95b.png)

**Pastebin.com of any relevant .yml files (if applicable)**
https://hastebin.com/afayixihab.bash (archer kit)
https://hastebin.com/ijiwuzixix.bash (booster kit)
https://hastebin.com/kexohulopa.bash (daily kit)
https://hastebin.com/ahapoboqik.coffeescript (fisherman kit)
https://hastebin.com/xidajojeyi.bash (gapple kit)
https://hastebin.com/xirezuzegi.bash (hiker kit)
https://hastebin.com/qegikobawu.bash (magician kit)
https://hastebin.com/azijutowod.bash (ninja kit)
https://hastebin.com/novimohayi.bash (reaper kit)
https://hastebin.com/heveloluso.bash (tank kit)

**Comment by cervinakuy** [comment]
kp.command.kit?

**Comment by muffinized** [comment]
no, even through the menu, but ill try that

**Comment by muffinized** [comment]
it worked lmaoooo
