### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DakshNamdev** [cervinakuy/KitPvP#95]
Able to execute commands after reaching certain level.
Example:
   Level-1: '&7Level %number%'
     Commands:
     - 'console: lp user %player% permission set kp.kit.archer' 
     Enabled: true

**Comment by cervinakuy** [comment]
Thanks, this has been added in [2163c97](https://github.com/cervinakuy/KitPvP/blob/master/src/main/java/com/planetgallium/kitpvp/game/Levels.java), and will be included in the next update.
